groups:
    - development
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: Brians MacBook Pro
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - sourcetree